### ISSUE TITLE
Profile pictures broken

### ISSUE THREAD

**Issue by bigchipbag** [CMPUT410W15/cmput410-project#125]
They work on the homepage but are broken on every other page. I'm not sure if we should keep them around if we don't have them working at all

**Comment by bigchipbag** [comment]
Also questioning why this was merged

**Comment by paul80** [comment]
oh yeah i might have forgot to mention, but i made it in previous commits so that only if you are viewing your own page can you see your profile picture. that might explain why profile pictures don't show up consistently over pages. i did this cause other servers' users may not have profile pictures, unless im wrong or logic is kinda off

**Comment by paul80** [comment]
on the authorpage at least, but feel free to correct any mistakes i may have made

**Comment by bigchipbag** [comment]
I'm not going to fix this. I'm going to do the video demos without any profile pictures because of the inconsistency
